name: ppg_example
description: Demonstrates how to use the ppg plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  permission_handler: ^4.0.0
  scoped_model: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  ppg:
    path: ../

flutter:
  uses-material-design: true
