name: ppg
description: A plugin to access a PPG sensor on WearOS devices
version: 0.0.1
homepage: http://stanford.edu/~kuprel

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.kuprel.ppg
    pluginClass: PpgPlugin
