name: ppg
description: A plugin to access the PPG sensor and estimated heart rate on WearOS devices.
version: 0.1.8
homepage: https://github.com/kuprel/ppg_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.kuprel.ppg
    pluginClass: PpgPlugin
